{
 "title": "Anduril Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "node_job", "query": "prysm-beacon" },
   {
    "name": "fiat",
    "label": "Currency converter",
    "query": {
     "query": "label_values(crypto_currency, pair)"
    }
   },
   { "name": "validator_launchpad", "query": "localhost:8081" },
   { "name": "validator_ethdo", "query": "localhost:8079" },
   { "name": "validator_job", "query": "prysm-validator" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "ANDURIL",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Hourly earning",
   "type": "stat",
   "description": "This panel shows the earning during the last hour, and the annualized % of the hourly earning.\n\nThose data won't be shown until the first validator is at least one hour old, or that you started prometheus at least one hour ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1h))*absent(crypto_currency{pair=~\"eth$fiat\"})",
     "legendFormat": "ETH"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1h))*sum(crypto_currency{pair=\"eth$fiat\"})",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1h)) / avg_over_time(sum(validator_balance)[1h:30s]) * 24 * 365 * 100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "ETH$",
   "type": "stat",
   "description": "Current price of ETH in USD.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ethprice{cur=\"USD\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETH Price",
   "type": "timeseries",
   "description": "Current price of ETH in $currency.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "ethprice{cur=\"USD\"}",
     "legendFormat": "{{cur}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "The mathematical expectation of time between proposals for an individual validator and across all local validators.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_current_active_validators{group=\"Prysm/Reth\",job=\"prysm-beacon\"} / scalar(count(validator_balance)) / 7200",
     "legendFormat": "~Time Between Proposals"
    }
   ]
  },
  {
   "title": "Base Fee per Gas",
   "type": "stat",
   "description": "Latest base fee per gas. Full support: Besu, Erigon, Geth, Nethermind",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (network) (execution_fee_base_fee_per_gas{group=\"Prysm/Reth\"})/1000000000",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Gas Used",
   "type": "gauge",
   "description": "The percentage of the gas limit used.",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max by (network) (besu_blockchain_chain_head_gas_used{group=\"Prysm/Reth\"}/besu_blockchain_chain_head_gas_limit{group=\"Prysm/Reth\"})) or\r\n(max by (network) (execution_fee_gas_used_ratio{group=\"Prysm/Reth\"})) or\r\n(max by (network) (eth_exe_block_head_gas_used{group=\"Prysm/Reth\"}/eth_exe_block_head_gas_limit{group=\"Prysm/Reth\"}))",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "description": "Current count of consensus and execution client peers. Full support: Besu, Erigon, Geth, Lighthouse, Lodestar, Nethermind, Nimbus, Prysm, Teku",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (group,service) (consensus_node_peer_count:connected{group=\"Prysm/Reth\"}) or\r\nmax by (group,service) (p2p_peer_count{group=\"Prysm/Reth\",state=\"Connected\",job!=\"prysmvalidator\"}) ",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "max by (group,service) (execution_net_peerCount{group=\"Prysm/Reth\"}) or\r\nmax by (group,service) (p2p_peers{group=\"Prysm/Reth\"}) or\r\nmax by (group,service) (reth_network_connected_peers{group=\"Prysm/Reth\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Daily earning",
   "type": "stat",
   "description": "This panel shows the earning during the last day, and the annualized % of the daily earning.\n\nThose data won't be shown until the first validator is at least one day old, or that you started prometheus at least one day ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1d))*absent(crypto_currency{pair=~\"eth$fiat\"})",
     "legendFormat": "ETH"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1d))*sum(crypto_currency{pair=\"eth$fiat\"})",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1d)) / avg_over_time(sum(validator_balance)[1d:12m]) * 365 * 100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "ETH Balance",
   "type": "stat",
   "description": "Sum of the current balance of all local validators",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (group,network) (validator_balance{group=\"Prysm/Reth\",job=\"prysm-validator\"}) or\r\nsum by (group,network) (consensus_validator_balance:ETH{group=\"Prysm/Reth Group\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Head Block",
   "type": "stat",
   "description": "Number of transactions, voluntary exits, attester slashings, and proposer slashing in the head block. Full support: Ethereum Metrics Exporter. Limited support: Besu.",
   "gridPos": { "h": 3, "w": 9, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (network) (besu_blockchain_chain_head_transaction_count{group=\"Prysm/Reth\"}) or max by (network) (eth_con_beacon_transactions{group=\"Prysm/Reth\",block_id=\"head\"})",
     "legendFormat": "Transactions"
    },
    {
     "expr": "max by (network) (eth_con_beacon_voluntary_exits{group=\"Prysm/Reth\",block_id=\"head\"})",
     "legendFormat": "Voluntary Exits"
    },
    {
     "expr": "eth_con_beacon_slashings{group=\"Prysm/Reth\",block_id=\"head\",type=\"attester\"}",
     "legendFormat": "Attester Slashings"
    },
    {
     "expr": "eth_con_beacon_slashings{group=\"Prysm/Reth\",block_id=\"head\",type=\"proposer\"}",
     "legendFormat": "Proposer Slashings"
    }
   ]
  },
  {
   "title": "Slots behind",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot{job=\"prysm-beacon\"}",
     "legendFormat": "Slots behind"
    }
   ]
  },
  {
   "title": "Upcoming Validator Duties",
   "type": "table",
   "description": "List of local validators and their scheduled attestations/proposals, and the amount of time remaining until those slots. Time remaining is as of the last Grafana data refresh. Full support: Prysm",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(max by (network,pubkey_short,index) (validator_next_proposal_slot{group=\"Prysm/Reth\"} > scalar(floor((time() - last_over_time(consensus_beacon_genesis_time{group=\"Prysm/Reth\"}[2h]))/12))))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(max by (network,pubkey_short,index) (validator_next_proposal_slot{group=\"Prysm/Reth\"} > scalar(floor((time() - last_over_time(consensus_beacon_genesis_time{group=\"Prysm/Reth\"}[2h]))/12)))) * 12 + scalar(max by (network) (last_over_time(consensus_beacon_genesis_time{group=\"Prysm/Reth\"}[2h])) -  time())",
     "legendFormat": "__auto"
    },
    {
     "expr": "(max by (network,pubkey_short,index) (validator_next_attestation_slot{group=\"Prysm/Reth\"} > scalar(floor((time() - last_over_time(consensus_beacon_genesis_time{group=\"Prysm/Reth\"}[2h]))/12))))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(max by (network,pubkey_short,index) (validator_next_attestation_slot{group=\"Prysm/Reth\"} > scalar(floor((time() - last_over_time(consensus_beacon_genesis_time{group=\"Prysm/Reth\"}[2h]))/12)))) * 12 + scalar(max by (network) (last_over_time(consensus_beacon_genesis_time{group=\"Prysm/Reth\"}[2h])) -  time())",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator main info",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_balance), \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_statuses), \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    }
   ]
  },
  {
   "title": "Total balance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (group,network) (validator_balance{group=\"Prysm/Reth\",job=\"prysm-validator\"}) or\nsum by (group,network) (consensus_validator_balance:ETH{group=\"Prysm/Reth\"})",
     "legendFormat": "Total balance"
    }
   ]
  },
  {
   "title": "Next Attestation",
   "type": "stat",
   "description": "Displays the current slot and the slot number for the next scheduled attestation across all local validators. Also displays the amount of time remaining until that slot. Time remaining is as of the last Grafana data refresh. Full support: Prysm",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (group,service,explorer) (floor((time() - last_over_time(consensus_beacon_genesis_time{group=\"Prysm/Reth\"}[2h]))/12))",
     "legendFormat": "Current Slot"
    },
    {
     "expr": "min by (group,network,explorer) (max by (group,network,pubkey,explorer) (validator_next_attestation_slot{group=\"Prysm/Reth\"} > scalar(floor((time() - last_over_time(consensus_beacon_genesis_time{group=\"Prysm/Reth\"}[2h]))/12))))",
     "legendFormat": "Next Attestation"
    },
    {
     "expr": "min by (group,network,explorer) (max by (group,network,pubkey,explorer) (validator_next_attestation_slot{group=\"Prysm/Reth\"} > scalar(floor((time() - last_over_time(consensus_beacon_genesis_time{group=\"Prysm/Reth\"}[2h]))/12)))) * 12 + scalar(max by (group,network,explorer) (last_over_time(consensus_beacon_genesis_time{group=\"Prysm/Reth\"}[2h])) -  time())",
     "legendFormat": "Time Remaining"
    }
   ]
  },
  {
   "title": "Validator vote summary",
   "type": "table",
   "description": "This panel will count only the votes done since your validator process started",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_attestations) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey)(validator_failed_attestations)  , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey)(validator_successful_aggregations)    , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_failed_aggregations) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_successful_proposals) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_failed_proposals) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    }
   ]
  },
  {
   "title": "Next Proposal",
   "type": "stat",
   "description": "Displays the current slot and the slot number for the next scheduled proposal across all local validators. Also displays the amount of time remaining until that slot. Time remaining is as of the last Grafana data refresh. Full support: Prysm",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (group,service,explorer) (floor((time() - last_over_time(consensus_beacon_genesis_time{group=\"Prysm/Reth\"}[2h]))/12))",
     "legendFormat": "Current Slot"
    },
    {
     "expr": "min by (group,network,explorer) (max by (group,network,pubkey) (validator_next_proposal_slot{group=\"Prysm/Reth\"} > scalar(floor((time() - last_over_time(consensus_beacon_genesis_time{group=\"Prysm/Reth\"}[2h]))/12)))) or on() vector(-1)",
     "legendFormat": "Proposal Slot"
    },
    {
     "expr": "min by (group,network,explorer) (max by (group,network,pubkey) (validator_next_proposal_slot{group=\"Prysm/Reth\"} > scalar(floor((time() - last_over_time(consensus_beacon_genesis_time{group=\"Prysm/Reth\"}[2h]))/12)))) * 12 + scalar(max by (group,network) (last_over_time(consensus_beacon_genesis_time{group=\"Goerli Prysm/Reth\"}[2h])) - time())",
     "legendFormat": "Time Remaining"
    }
   ]
  },
  {
   "title": "Balance validators status and participation rate",
   "type": "graph",
   "description": "This graph is made for trading purpose mostly.\nSupposing that if a lot of validators are exiting, price is gonna dump.\n\nAlso this can prevent to exit while exiting queue is too long, same for depositing while pending queue is too long.\n\n",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "validators_total_balance{state=\"Active\"} / 10e8",
     "legendFormat": "Active"
    },
    {
     "expr": "validators_total_balance{state=\"Pending\"} / 10e8",
     "legendFormat": "Pending"
    },
    {
     "expr": "validators_total_balance{state=\"Exiting\"} / 10e8",
     "legendFormat": "Exiting"
    },
    {
     "expr": "beacon_prev_epoch_target_gwei/beacon_prev_epoch_active_gwei*100",
     "legendFormat": "Participation rate"
    }
   ]
  },
  {
   "title": "ALERTS",
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Hourly Logs",
   "type": "bargauge",
   "description": "This panel won't have consistant values during the first hour of the node started process",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{job=\"$node_job\", level=\"error\"}[1h]) > 0)",
     "legendFormat": "error"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"$node_job\", level=\"warning\"}[1h]) > 0)",
     "legendFormat": "warning"
    }
   ]
  },
  {
   "title": "Software:",
   "type": "table",
   "description": "Software client details, including version, latest release, uptime, and database size. Full support: Erigon,  Lighthouse, Prysm. Partial support: Besu, Ethereum Metrics Exporter, Geth, Lodestar, Nethermind, Nimbus, Teku",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "(\r\ntopk by (service) (1,version{group=\"Prysm/Reth\"}) or\r\non(service) topk by (service) (1,lighthouse_info{group=\"Prysm/Reth\"}) or\r\non(service) topk by (service) (1,prysm_version{group=\"Prysm/Reth\"}) or\r\non(service) topk by (service) (1,beacon_teku_version{group=\"Prysm/Reth\"}) or\r\non(service) topk by (service) (1,execution_version{group=\"Prysm/Reth\"}) or\r\non(service) topk by (service) (1,prometheus_build_info{group=\"Prysm/Reth\"}) or\r\non(service) topk by (service) (1,lodestar_version{group=\"Prysm/Reth\"}) or\r\non(service) topk by (service) (1,blackbox_exporter_build_info{group=\"Prysm/Reth\"}) or\r\non(service) topk by (service) (1,node_exporter_build_info{group=\"Prysm/Reth\"}) or\r\non(service) topk by (service) (1,dirk_release{group=\"Prysm/Reth\"}) or\r\non(service) topk by (service) (1,vouch_release{group=\"Prysm/Reth\"}) or\r\non(service) topk by (service) (1,process_start_time_seconds{group=\"Prysm/Reth\"}) or\r\non(service) topk by (service) (1,eth_exe_web3_client_version{group=\"Prysm/Reth\"}) or\r\non(service) topk by (service) (1,eth_con_node_version{group=\"Prysm/Reth\"})\r\n) * on(client) group_left(tag_name,html_url) topk by (client) (1,last_over_time(release_id{client!=\"\"}[2h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk by (service) (1,(time() - process_start_time_seconds{group=\"Prysm/Reth\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (service) (bcnode_disk_beaconchain_bytes_total{group=\"Prysm/Reth\"}) or\r\nsum by (service) (eth_db_chaindata_disk_size{group=\"Prysm/Reth\"} + eth_db_chaindata_ancient_size{group=\"Prysm/Reth\"}) or\r\nsum by (service) (db_size{group=\"Prysm/Reth\"}) or\r\nsum by (service) (store_disk_db_size{group=\"Prysm/Reth\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert: 50 slots behind",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot",
     "legendFormat": "node slots behind"
    }
   ]
  },
  {
   "title": "Alert: Participation rate < 75%",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "beacon_prev_epoch_target_gwei/beacon_prev_epoch_active_gwei*100"
    }
   ]
  },
  {
   "title": "Process CPU Seconds (per minute)",
   "type": "timeseries",
   "description": "Number of CPU seconds used by client software per minute. Full support: Besu, blackbox_exporter, Erigon, Ethereum Metrics Exporter, json_exporter, Lighthouse, Lodestar, Nethermind, Nimbus, node_exporter, Prometheus, Prysm, Teku. No support: Geth",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(process_cpu_seconds_total[1m]))*60",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Alert: Hourly earning <= 0",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(validator_balance) - sum(validator_balance offset 1h)",
     "legendFormat": "validators earning on 1h"
    }
   ]
  }
 ]
}